<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_BuyNow</name>
   <tag></tag>
   <elementGuidId>29306bdd-3c20-4bbd-9976-8b1335be10e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.buy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.buy</value>
   </webElementProperties>
</WebElementEntity>
