<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_CheckOut</name>
   <tag></tag>
   <elementGuidId>21271997-03c8-4cb1-b2b3-10492df42dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.cart-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.cart-checkout</value>
   </webElementProperties>
</WebElementEntity>
