<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_PayNow</name>
   <tag></tag>
   <elementGuidId>a8f2aeb7-1ad4-45fb-a05d-f29efd050e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.button-main-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.button-main-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[.='Pay Now']</value>
   </webElementProperties>
</WebElementEntity>
