<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disc_10Percent</name>
   <tag></tag>
   <elementGuidId>7da67d80-16be-4822-b35f-804bc552e552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input-row']/div[2]//input[@name='promo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input-row']/div[2]//input[@name='promo']</value>
   </webElementProperties>
</WebElementEntity>
